#SPDX-License-Identifier: MIT-0
---
# tasks file for weserver.role
- name: task 1 install apache2
  package:
   name: "{{pkg}}"
   state: latest
   enable: true
- name: change index page
  copy: 
   src: index.html
   dest: /var/www/html/index.html
   notify:
     - restart apache2

